services:
  - type: web
    name: school-management-system
    runtime: python-3-12
    buildCommand: "./build.sh"
    startCommand: "gunicorn sms_core.wsgi:application --log-file -"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.9"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "sms_core.settings"
      - key: ALLOWED_HOSTS
        value: "Educlique-school-management-system.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://Educlique-school-management-system.onrender.com"
      - key: DEFAULT_ADMIN_USERNAME
        value: "admin"
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
    databases:
      - name: school-db
        plan: free
