# Generated by Django 4.2.7 on 2026-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_schoolholiday_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolholiday',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='schoolholiday',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for a single-day holiday', null=True),
        ),
        migrations.AlterField(
            model_name='schoolholiday',
            name='start_date',
            field=models.DateField(),
        ),
    ]
