# Generated by Django 4.2.7 on 2026-08-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0015_add_guardian_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('PAYROLL', 'Payroll'), ('FOOD', 'Food & Kitchen'), ('UTILITIES', 'Utilities'), ('SUPPLIES', 'Learning & Office Supplies'), ('MAINTENANCE', 'Maintenance & Repairs'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='CASH', max_length=30)),
                ('reference_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='PAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-expense_date', '-id']},
        ),
        migrations.CreateModel(
            name='LunchEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], default='TERM_1', max_length=10)),
                ('year', models.IntegerField(default=2026)),
                ('amount', models.DecimalField(decimal_places=2, default=3000.0, max_digits=12)),
                ('is_enrolled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_enrollments', to='finance.student')),
            ],
            options={'ordering': ['student__admission_number'], 'unique_together': {('student', 'term', 'year')}},
        ),
    ]
