# Generated by Django 4.2.7 on 2026-08-17 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0017_userprofile_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=10),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('STUDENT_DELETION', 'Student Record Deletion'), ('GRADE_PROMOTION', 'Grade Promotion'), ('BALANCE_ADJUSTMENT', 'Balance Adjustment'), ('INVOICE_ADJUSTMENT', 'Invoice Adjustment')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, help_text='Reason for the request')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'approval_type', 'created_at'], name='finance_app_status_30c49a_idx'), models.Index(fields=['requested_by', 'status'], name='finance_app_request_40d737_idx')],
            },
        ),
    ]
